version: "3.8"
services:
  postgres:
    image: postgres:15.1-alpine3.17
    container_name: postgres
    restart: always
    env_file:
      - Smart-Pot-API/.env
    environment:
      PGDATA: /data/
    volumes:
      - ./Smart-Pot-API/database:/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
  api:
    build:
      context: ./Smart-Pot-API
      dockerfile: Dockerfile
    container_name: api
    restart: always
    env_file:
      - Smart-Pot-API/.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./Smart-Pot-API/app:/smart_pot_api/app
      - ./Smart-Pot-API/alembic.ini:/smart_pot_api/alembic.ini
      - ./Smart-Pot-API/alembic:/smart_pot_api/alembic