name: Tests API
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_TEST_DB: ${{ secrets.POSTGRES_DB }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      TEST_DATABASE_URL: "postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/${{ secrets.POSTGRES_DB }}"
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build the Docker containers
      run: docker-compose -f "test-docker-compose.yaml" build
    - name: Run Application with Docker Compose
      run: docker-compose -f "test-docker-compose.yaml" up -d
    - name: Check logs from postgres container
      run: docker-compose -f "test-docker-compose.yaml" logs postgres
    - name: Run the tests
      run: docker-compose -f "test-docker-compose.yaml" run api pytest tests/
